apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
  labels:
    app: insurance-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      containers:
      - name: insurance-app
        image: ${DOCKER_REGISTRY}/insurance-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: insurance-app-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: insurance-app-config
              key: db_port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: insurance-app-secrets
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: insurance-app-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: insurance-app-secrets
              key: db_password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 